# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  devcontainerapi:
    image: devcontainerapi
    build:
      context: .
      dockerfile: Services/DevContainer/DevContainer.API/Dockerfile
    ports:
      - 5100:5100
